import type { NextPage } from "next";
import Head from "next/head";
import { Container, Typography, Stack } from "@mui/material";
import Link from "next/link";

const Home: NextPage = () => {
  return (
    <Container maxWidth="md">
      <Head>
        <title>Simulations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Typography variant="h3" component="h1" style={{ marginTop: "1rem" }}>
        3d simulations
      </Typography>

      <Typography variant="subtitle1">
        Just a bunch of simulations I&apos;ve made for educational purposes. I
        suggest using desktop for optimal experience.
      </Typography>

      <Stack spacing={2} style={{ marginTop: "4rem" }}>
        <Link href={"/naive-cube"}>Naive Cube</Link>
        <Link href={"/naive-cube"}>Cube with noise</Link>
        <Link href={"/optimize-mesh"}>Optimize Mesh</Link>
        <Link href={"/ray-casting-2d"}>Ray Casting 2D</Link>
      </Stack>
    </Container>
  );
};

export default Home;
